# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/realworld
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# JWT
app.jwtSecret=JWTSuperSecretKey
app.jwtExpirationInMs=604800000

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.realworld.com=DEBUG